# Generated by Django 4.2.9 on 2026-01-21 22:23

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('general', 'General Assessment'), ('overweight', 'Overweight Assessment')], max_length=20)),
                ('general_health', models.CharField(choices=[('Good', 'Good'), ('Poor', 'Poor')], max_length=10)),
                ('on_diet', models.BooleanField(blank=True, help_text='For overweight assessment: Have you ever been on a diet to lose weight?', null=True)),
                ('using_drugs', models.BooleanField(blank=True, help_text='For general assessment: Are you currently using any drugs?', null=True)),
                ('comments', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(db_index=True, help_text='Unique patient identifier', max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-registration_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('height', models.DecimalField(decimal_places=2, help_text='Height in centimeters', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('30.0')), django.core.validators.MaxValueValidator(Decimal('300.0'))])),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kilograms', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1.0')), django.core.validators.MaxValueValidator(Decimal('500.0'))])),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, help_text='Body Mass Index (auto-calculated)', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.patient')),
            ],
            options={
                'ordering': ['-visit_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['patient_id'], name='patients_pa_patient_927c52_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['last_name', 'first_name'], name='patients_pa_last_na_1b32a7_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['-registration_date'], name='patients_pa_registr_c72f68_idx'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='visit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='patients.visit'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['patient', '-visit_date'], name='patients_vi_patient_494a7c_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['-visit_date'], name='patients_vi_visit_d_c06751_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='visit',
            unique_together={('patient', 'visit_date')},
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['visit'], name='patients_as_visit_i_0e07ac_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['assessment_type'], name='patients_as_assessm_7da0a3_idx'),
        ),
    ]
